name: ETL ML Pipeline

on:

  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 6 * * *'


jobs:

  etl_pipeline:

    runs-on: ubuntu-latest

    steps:

      # =====================================
      # CLONAR REPOSITORIO
      # =====================================
      - name: Checkout repository
        uses: actions/checkout@v4


      # =====================================
      # CONFIGURAR PYTHON
      # =====================================
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      # =====================================
      # INSTALAR DEPENDENCIAS
      # =====================================
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # =====================================
      # EJECUTAR ETL BRONZE
      # =====================================
      - name: Run ETL Bronze
        run: |
          python etl/etl_bronze.py


      # =====================================
      # EJECUTAR ETL GOLD ML
      # =====================================
      - name: Run ETL Gold ML
        run: |
          python etl/etl_gold.py


      # =====================================
      # INSTALAR POSTGRESQL 17 CLIENT
      # =====================================
      - name: Install PostgreSQL 17 Client
        run: |

          sudo apt-get update

          sudo apt-get install -y wget gnupg2

          echo "deb http://apt.postgresql.org/pub/repos/apt noble-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

          wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

          sudo apt-get update

          sudo apt-get install -y postgresql-client-17


     
      # =====================================
      # FIN
      # =====================================
      - name: Pipeline finished
        run: echo "🚀 ETL + ML + BACKUP ejecutado correctamente"
